services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: signet-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      # Laravel tidak perlu lagi akses hardware langsung
      # - /dev:/dev

    # privileged: true # <-- Bisa di-disable karena urusan USB sudah di-handle hsm

    ports:
      - "8888:8000"
      - "5173:5173"
    depends_on:
      - db
      - redis
      - hsm # <-- Tambahkan ini agar Laravel menunggu HSM menyala dulu

    # ---Enable when first build, disable later---
    # command: sleep infinity

    # ---Enable after first build, disable before first build---
    command: zsh -c "php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000 --watch"

  # ==========================================
  # SERVICE: Node.js Micro HSM Bridge
  # ==========================================
  hsm:
    build:
      context: ./hsm-bridge
      dockerfile: Dockerfile
    container_name: signet-hsm
    restart: unless-stopped
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    ports:
      - "3000:3000"
    environment:
      - SERIAL_PORT=/dev/ttyUSB0

  db:
    image: postgres:18-alpine
    container_name: signet-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  redis:
    image: redis:8-alpine
    container_name: signet-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  db_data:
  redis_data:
