<?php

namespace App\Http\Controllers\Pages;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Log;
use App\Models\Product;
use App\Services\HsmService;
use Exception;

class ProductController extends Controller
{
    public function index()
    {
        /** @var \App\Models\User $user */
        $user = Auth::user();
        $workspace = $user->workspaces()->first();
        $products = Product::where('workspace_id', $workspace->id)->withCount('licenses')->get();

        return view('pages.products.index', compact('user', 'workspace', 'products'));
    }

    public function store(Request $request, HsmService $hsm)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:100'],
            'description' => ['nullable', 'string', 'max:255'],
        ]);

        /** @var \App\Models\User $user */
        $user = Auth::user();
        $workspace = $user->workspaces()->first();

        try {
            $hsmResponse = $hsm->generateProductIdentity([
                'product_name' => $request->name,
                'organization' => 'Signet Cloud KMS',
            ]);

            // Validasi kelengkapan data dari Hardware
            if (!$hsmResponse || !isset($hsmResponse['data']['raw_private_key']) || !isset($hsmResponse['data']['certificate'])) {
                Log::error('[HSM PARSE ERROR] Invalid or incomplete JSON structure from Hardware.', [
                    'product_name' => $request->name
                ]);
                return back()->with('error', 'Hardware Security Error: HSM failed to respond or format is invalid.');
            }

            // Simpan ke Database dengan Private Key terenkripsi AES-256
            $workspace->products()->create([
                'name' => $request->name,
                'slug' => Str::slug($request->name) . '-' . Str::random(5),
                'description' => $request->description,
                'private_key' => Crypt::encryptString($hsmResponse['data']['raw_private_key']),
                'certificate' => $hsmResponse['data']['certificate'],
            ]);

            Log::info('[DB SUCCESS] Product and keys securely generated and saved for: ' . $request->name);
        } catch (Exception $e) {
            Log::error('[CRITICAL ERROR] Failed during product creation: ' . $e->getMessage());
            return back()->with('error', 'System Error: ' . $e->getMessage());
        }

        return back()->with('success', 'Product added successfully. Keys securely generated by Signet HSM.');
    }

    public function destroy($id)
    {
        /** @var \App\Models\User $user */
        $user = Auth::user();
        $workspace = $user->workspaces()->first();
        $product = $workspace->products()->where('id', $id)->firstOrFail();

        $product->delete();

        return back()->with('success', 'Product deleted successfully.');
    }

    public function downloadCert($id)
    {
        /** @var \App\Models\User $user */
        $user = Auth::user();
        $workspace = $user->workspaces()->first();
        $product = $workspace->products()->where('id', $id)->firstOrFail();

        if (empty($product->certificate)) {
            return back()->with('error', 'Certificate has not been generated for this product yet.');
        }

        $fileName = $product->slug . '-public.cert';

        return response($product->certificate, 200, [
            'Content-Type' => 'application/x-x509-ca-cert',
            'Content-Disposition' => 'attachment; filename="' . $fileName . '"',
        ]);
    }
}
