<?php

namespace App\Http\Controllers\Pages;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Crypt;
use App\Models\Product;
use App\Services\HsmService;

class ProductController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        $workspace = $user->workspaces()->first();
        $products = Product::where('workspace_id', $workspace->id)->withCount('licenses')->get();

        return view('pages.products.index', compact('user', 'workspace', 'products'));
    }

    public function store(Request $request, HsmService $hsm)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:100'],
            'description' => ['nullable', 'string', 'max:255'],
        ]);

        $workspace = Auth::user()->workspaces()->first();

        try {
            $hsmResponse = $hsm->generateProductIdentity([
                'product_name' => $request->name,
                'organization' => 'Signet Cloud KMS',
            ]);

            if (!$hsmResponse || !isset($hsmResponse['encrypted_private_key']) || !isset($hsmResponse['certificate'])) {
                return back()->with('error', 'Hardware Security Error: HSM failed to respond or create keys.');
            }

            $encryptedPrivateKey = $hsmResponse['encrypted_private_key'];
            $certificatePem = $hsmResponse['certificate'];
        } catch (\Exception $e) {
            return back()->with('error', 'Hardware Security Connection Failed: ' . $e->getMessage());
        }

        $workspace->products()->create([
            'name' => $request->name,
            'slug' => Str::slug($request->name) . '-' . Str::random(5),
            'description' => $request->description,
            'private_key' => $encryptedPrivateKey,
            'certificate' => $certificatePem,
        ]);

        return back()->with('success', 'Product added successfully. Keys securely generated by Signet HSM.');
    }

    public function destroy($id)
    {
        $workspace = Auth::user()->workspaces()->first();
        $product = $workspace->products()->where('id', $id)->firstOrFail();
        $product->delete();

        return back()->with('success', 'Product deleted successfully.');
    }

    public function downloadCert($id)
    {
        $workspace = Auth::user()->workspaces()->first();
        $product = $workspace->products()->where('id', $id)->firstOrFail();

        if (empty($product->certificate)) {
            return back()->with('error', 'Certificate has not been generated for this product yet.');
        }

        $fileName = $product->slug . '-public.cert';

        return response($product->certificate, 200, [
            'Content-Type' => 'application/x-x509-ca-cert',
            'Content-Disposition' => 'attachment; filename="' . $fileName . '"',
        ]);
    }
}
