<?php

namespace App\Http\Controllers\Pages;

use App\Http\Controllers\Controller;
use App\Http\Requests\Product\StoreProductRequest;
use App\Models\Product;
use App\Services\Products\ProductService;
use Illuminate\Support\Facades\Auth;
use Exception;

class ProductController extends Controller
{
    protected ProductService $productService;

    public function __construct(ProductService $productService)
    {
        $this->productService = $productService;
    }

    public function index()
    {
        /** @var \App\Models\User $user */
        $user = Auth::user();
        $workspace = $user->workspace()->first();
        $products = Product::where('workspace_id', $workspace->id)->withCount('licenses')->get();

        return view('pages.products.index', compact('user', 'workspace', 'products'));
    }

    public function store(StoreProductRequest $request)
    {
        try {
            /** @var \App\Models\User $user */
            $user = Auth::user();
            $workspace = $user->workspaces()->first();

            $this->productService->createProduct($workspace, $request->validated());

            return back()->with('success', 'Product added successfully. Keys securely generated by Signet HSM');
        } catch (Exception $e) {
            return back()->with('error', $e->getMessage());
        }
    }

    public function destroy($id)
    {
        /** @var \App\Models\User $user */
        $user = Auth::user();
        $workspace = $user->workspaces()->first();
        $product = $workspace->products()->where('id', $id)->firstOrFail();
        $product->delete();

        return back()->with('success', 'Product deleted successfully.');
    }

    public function downloadCert($id)
    {
        /** @var \App\Models\User $user */
        $user = Auth::user();
        $workspace = $user->workspaces()->first();
        $product = $workspace->products()->where('id', $id)->firstOrFail();

        if (empty($product->certificate)) {
            return back()->with('error', 'Certificate has not been generated for this product yet.');
        }

        return response($product->certificate, 200, [
            'Content-Type' => 'application/x-x509-ca-cert',
            'Content-Disposition' => 'attachment; filename="' . $product->slug . '"',
        ]);
    }
}
